[workspace]
resolver = "2"
members = [
    "proto",
    "types",
]

[workspace.dependencies]
celestia-proto = { version = "0.1.0", path = "proto" }
celestia-types = { version = "0.1.0", path = "types" }
